# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 28dd33df351b3b405692d31f06b5cb323d81981f1548572ee132dbeda5f8ed90beff47d519c249e79e6734aa2c856af9fe7d9c87cc34d84480b2725c71cd7c68

test:
  secret_key_base: 18faea86f883659273b4c89c8aead35020211c2021fc6d933ec13ff7fc8e1776cb59f1f3c8df7e0a2f9dee89a9fe721c61f1dc723d3d3efe3e957a73ad0a4267

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
